import uuid
from datetime import datetime
from app.database import get_db_cursor
import logging

logger = logging.getLogger(__name__)

class AuditService:
    def create_audit_tables_if_not_exist(self):
        with get_db_cursor() as cursor:
            if not cursor:
                return
            try:
                # Basic check for existence, if failing, we try to create
                cursor.execute("SELECT count(*) FROM CSV_IMPORT_BATCH")
            except Exception:
                try:
                    cursor.execute("""
                        CREATE TABLE CSV_IMPORT_BATCH (
                            BATCH_ID VARCHAR2(50) PRIMARY KEY,
                            IMPORT_TYPE VARCHAR2(100),
                            SOURCE_FILE_NAME VARCHAR2(255),
                            TARGET_TABLE VARCHAR2(100),
                            FILE_HASH VARCHAR2(255),
                            STARTED_AT TIMESTAMP,
                            COMPLETED_AT TIMESTAMP,
                            TOTAL_RECORDS NUMBER,
                            PROCESSED_RECORDS NUMBER,
                            INSERTED_RECORDS NUMBER,
                            DUPLICATE_RECORDS NUMBER,
                            FAILED_RECORDS NUMBER,
                            STATUS VARCHAR2(50),
                            FAILED_LOG_FILE VARCHAR2(255),
                            ERROR_MESSAGE VARCHAR2(1000)
                        )
                    """)
                    cursor.execute("""
                        CREATE TABLE CSV_IMPORT_RECORD_AUDIT (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            BATCH_ID VARCHAR2(50),
                            IMPORT_TYPE VARCHAR2(100),
                            TARGET_TABLE VARCHAR2(100),
                            RECORD_HASH VARCHAR2(255),
                            SOURCE_ROW_NUMBER NUMBER,
                            STATUS VARCHAR2(50),
                            ERROR_MESSAGE VARCHAR2(1000),
                            PROCESSED_AT TIMESTAMP
                        )
                    """)
                    cursor.execute("CREATE INDEX idx_csv_audit_hash ON CSV_IMPORT_RECORD_AUDIT(RECORD_HASH)")
                except Exception as e:
                    logger.error(f"Failed to create audit tables: {e}")

    def create_batch(self, file_name, file_hash, import_type, target_table):
        # Auto-purge logs older than 7 days on new batch creation
        self.purge_logs_older_than_days(days=7)

        batch_id = str(uuid.uuid4())
        with get_db_cursor() as cursor:
            if cursor:
                cursor.execute("""
                    INSERT INTO CSV_IMPORT_BATCH (
                        BATCH_ID, IMPORT_TYPE, SOURCE_FILE_NAME, TARGET_TABLE, FILE_HASH, STARTED_AT, STATUS
                    ) VALUES (
                        :1, :2, :3, :4, :5, SYSTIMESTAMP, 'PROCESSING'
                    )
                """, (batch_id, import_type, file_name, target_table, file_hash))
        return batch_id

    def update_batch(self, batch_id, result_data):
        with get_db_cursor() as cursor:
            if cursor:
                cursor.execute("""
                    UPDATE CSV_IMPORT_BATCH SET
                        COMPLETED_AT = SYSTIMESTAMP,
                        TOTAL_RECORDS = :1,
                        PROCESSED_RECORDS = :2,
                        INSERTED_RECORDS = :3,
                        DUPLICATE_RECORDS = :4,
                        FAILED_RECORDS = :5,
                        STATUS = :6,
                        FAILED_LOG_FILE = :7
                    WHERE BATCH_ID = :8
                """, (
                    result_data.get('total_records', 0),
                    result_data.get('processed_records', 0),
                    result_data.get('inserted_records', 0),
                    result_data.get('duplicate_records', 0),
                    result_data.get('failed_records', 0),
                    result_data.get('status', 'COMPLETED'),
                    result_data.get('failed_log_file'),
                    batch_id
                ))

    def check_if_duplicate(self, record_hash):
        with get_db_cursor() as cursor:
            if cursor:
                cursor.execute("SELECT count(*) FROM CSV_IMPORT_RECORD_AUDIT WHERE RECORD_HASH = :1 AND STATUS = 'INSERTED'", (record_hash,))
                result = cursor.fetchone()
                if result and result[0] > 0:
                    return True
        return False
        
    def log_record(self, batch_id, import_type, target_table, record_hash, row_number, status, error_msg=""):
        with get_db_cursor() as cursor:
            if cursor:
                cursor.execute("""
                    INSERT INTO CSV_IMPORT_RECORD_AUDIT (
                        BATCH_ID, IMPORT_TYPE, TARGET_TABLE, RECORD_HASH, SOURCE_ROW_NUMBER, STATUS, ERROR_MESSAGE, PROCESSED_AT
                    ) VALUES (
                        :1, :2, :3, :4, :5, :6, :7, SYSTIMESTAMP
                    )
                """, (batch_id, import_type, target_table, record_hash, row_number, status, str(error_msg)[:1000]))

    def purge_logs_older_than_days(self, days=7):
        """
        Auto-delete import logs and record audit entries older than N days (default: 7 days).
        Also deletes associated failed CSV log files from disk.
        """
        import os
        FAILED_LOGS_DIR = "logs/failed"
        with get_db_cursor() as cursor:
            if not cursor:
                return 0
            try:
                cursor.execute("""
                    SELECT BATCH_ID, FAILED_LOG_FILE FROM CSV_IMPORT_BATCH
                    WHERE STARTED_AT < (SYSTIMESTAMP - NUMTODSINTERVAL(:1, 'DAY'))
                """, (days,))
                old_batches = cursor.fetchall()
                if not old_batches:
                    return 0

                deleted_count = len(old_batches)
                for b in old_batches:
                    b_id = b[0]
                    failed_file = b[1]
                    if failed_file:
                        filepath = os.path.join(FAILED_LOGS_DIR, failed_file)
                        if os.path.exists(filepath):
                            try:
                                os.remove(filepath)
                            except Exception:
                                pass
                    cursor.execute("DELETE FROM CSV_IMPORT_RECORD_AUDIT WHERE BATCH_ID = :1", (b_id,))
                    cursor.execute("DELETE FROM CSV_IMPORT_BATCH WHERE BATCH_ID = :1", (b_id,))

                logger.info(f"Auto-purged {deleted_count} import batch log(s) older than {days} days.")
                return deleted_count
            except Exception as e:
                logger.warning(f"7-day log auto-purge notice: {e}")
                return 0

audit_service = AuditService()
